### ISSUE TITLE
Latest update stopped reading from SD2

### ISSUE THREAD

**Issue by elmoiv** [AeolusUX/ArkOS-R3XS-Updater#1]
After Installing 04022024 Update to my R36S. All games are gone. When I tried to switch for SD2 for games it opens black screen without any info then goes back to settings menu again.

Tried to turn R36S off and on with\without the SD2. But nothing helps.

What happened?

**Comment by AeolusUX** [comment]
Is this updated via OTA or with the full image?

**Comment by elmoiv** [comment]
via OTA.

I fixed the problem by reflashing the image on sd1.

Whenever I update, I will switch to SD1 then after update switch again to sd2
