### ISSUE TITLE
Problem with updater

### ISSUE THREAD

**Issue by OPKiller98** [AeolusUX/ArkOS-R3XS-Updater#3]
Hello, when I click OK when trying to update the console. He tells me I haven't written it. What do I have to do to solve it?

**Comment by gdamoreira** [comment]
Someone changed `OK` to `TEST` (https://github.com/AeolusUX/ArkOS-R3XS-Updater/commit/b2c8a27fcf109c08c32c2656830385508b47bcc4) in previous versions, type `TEST` and it will update.

**Comment by AeolusUX** [comment]
> Someone changed `OK` to `TEST` ([b2c8a27](https://github.com/AeolusUX/ArkOS-R3XS-Updater/commit/b2c8a27fcf109c08c32c2656830385508b47bcc4)) in previous versions, type `TEST` and it will update.

There's a reason why it gets changed to that before I release an update. Goodluck fixing your install if you try to update before release.
